import csv

questions = [
    {"q": "21", "text": "21 The graph shows the relationship between force acting on a compression spring and change in length of the spring.\n[diagram]\nOne of these springs is placed in each corner of a horizontal square plate. The axis of each spring is in a vertical direction. These four springs support a total load of 160 N.\nWhat is the total elastic potential energy stored in the four springs?\nA 0.048 J\nB 0.19 J\nC 0.38 J\nD 0.77 J", "img": "images/9702_m25_qp_12_q21.png"},
    {"q": "22", "text": "22 Which row correctly identifies the properties of all electromagnetic waves?\n[diagram]\nA transverse wave: yes, longitudinal wave: no, can travel in free space: yes\nB transverse wave: no, longitudinal wave: yes, can travel in free space: yes\nC transverse wave: yes, longitudinal wave: no, can travel in free space: no\nD transverse wave: yes, longitudinal wave: yes, can travel in free space: yes", "img": "images/9702_m25_qp_12_q22.png"},
    {"q": "23", "text": "23 What is the approximate range of wavelengths in free space for infrared radiation?\nA 100 nm to 400 nm\nB 300 μm to 30 cm\nC 400 nm to 700 nm\nD 800 nm to 1000 μm", "img": "NULL"},
    {"q": "24", "text": "24 The diagram shows a car travelling at a constant speed in a straight line between person P and person Q from point X to point Y.\n[diagram]\nThe car sounds its horn continuously as it travels. The horn emits sound of constant frequency.\nWhich statements about what person P and person Q hear during the motion of the car are correct?\n1 Person P hears a sound of increasing frequency.\n2 Person Q hears a sound of decreasing frequency.\n3 Person Q always hears a sound of higher frequency than person P.\nA 1, 2 and 3\nB 1 and 2 only\nC 3 only\nD none of them", "img": "images/9702_m25_qp_12_q24.png"},
    {"q": "25", "text": "25 A progressive wave of frequency 300 Hz is travelling with a speed of 600 m s–1.\nWhat is the phase difference between two points on the wave that are a distance of 0.50 m apart?\nA 45°\nB 90°\nC 180°\nD 360°", "img": "NULL"},
    {"q": "26", "text": "26 A polarised beam of light with intensity I is incident normally on a polarising filter.\nThe transmitted light has intensity I.\nThe filter is rotated about the normal axis through an angle θ.\nThe transmitted light has intensity 0.75 I.\nWhat is the angle θ ?\nA 30°\nB 42°\nC 49°\nD 60°", "img": "NULL"},
    {"q": "27", "text": "27 Light waves are emitted from two sources.\nWhat is a necessary condition for observable interference fringes to be produced?\nA The waves must be polarised.\nB The waves must not be polarised.\nC The waves must be coherent.\nD The waves must have equal amplitudes.", "img": "NULL"},
    {"q": "28", "text": "28 The diagram shows a water wave in a shallow tank. The wave is diffracted through a gap in a barrier and spreads. The wavelength of the wave is much smaller than the width of the gap.\n[diagram]\nThe wavelength of the wave and the width of the gap are both changed by a small amount.\nWhich combination of changes must increase the amount of spreading due to diffraction?\nA wavelength decreases, width of gap decreases\nB wavelength decreases, width of gap increases\nC wavelength increases, width of gap decreases\nD wavelength increases, width of gap increases", "img": "images/9702_m25_qp_12_q28.png"},
    {"q": "29", "text": "29 Light of wavelength 567 nm is incident normally on a diffraction grating. The grating has 400 lines per mm. A number of diffraction maxima are observed on the far side of the grating.\nWhat is the angle between the second-order maximum and the third-order maximum?\nA 13.1°\nB 13.9°\nC 15.9°\nD 27.0°", "img": "NULL"},
    {"q": "30", "text": "30 Two cylindrical conductors, X and Y, are made from the same material. The conductors have equal lengths, but Y has a smaller diameter than X.\nX and Y are connected in series to a cell.\nWhich row compares the number of charge carriers per unit time passing through X and through Y and compares the average drift speed of the charge carriers in X and in Y?\nA Y greater than X, Y greater than X\nB Y same as X, Y same as X\nC Y greater than X, Y same as X\nD Y same as X, Y greater than X", "img": "NULL"},
    {"q": "31", "text": "31 A copper wire is 6.4 m long and has a resistance of 0.92 Ω.\nThe resistivity of copper is 1.8 × 10–8 Ω m.\nWhat is the diameter of the wire?\nA 5.7 × 10–5 m\nB 1.0 × 10–4 m\nC 4.0 × 10–4 m\nD 7.1 × 10–4 m", "img": "NULL"},
    {"q": "32", "text": "32 A thermistor is connected to a cell with negligible internal resistance.\nWhich graph shows the variation with temperature of power, P, dissipated in the thermistor?\n[diagram]\nA, B, C, D", "img": "images/9702_m25_qp_12_q32.png"},
    {"q": "33", "text": "33 A metal electrical conductor has a resistance of 5.6 kΩ. A potential difference (p.d.) of 9.0 V is applied across its ends.\nHow many electrons pass a point in the conductor in one minute?\nA 6.0 × 10^20\nB 1.0 × 10^19\nC 6.0 × 10^17\nD 1.0 × 10^16", "img": "NULL"},
    {"q": "34", "text": "34 Which circuit symbol does not represent an electric component that is designed to emit sound waves?\n[diagram]\nA B C D", "img": "images/9702_m25_qp_12_q34.png"},
    {"q": "35", "text": "35 The diagram shows a junction in a circuit where three wires, P , Q and R, meet. The currents in P and Q are 1 A and 3 A respectively, in the directions shown.\n[diagram]\nHow much charge passes a given point in wire R in a time of 5 s?\nA 0.4 C\nB 2 C\nC 10 C\nD 20 C", "img": "images/9702_m25_qp_12_q35.png"},
    {"q": "36", "text": "36 A cell of electromotive force (e.m.f.) E and internal resistance r is connected in series with a switch S and an external resistor of resistance R.\n[diagram]\nThe potential difference (p.d.) between P and Q is V.\nWhich statement is correct when S is changed from open to closed?\nA V increases because there is a p.d. across R.\nB V decreases because there is a p.d. across r.\nC V remains the same because the decrease of p.d. across r is balanced by the increase of p.d. across R.\nD V remains the same because the sum of the p.d.s across r and R is still equal to E.", "img": "images/9702_m25_qp_12_q36.png"},
    {"q": "37", "text": "37 What is a general description of a baryon?\nA It consists of three quarks that must all be the same flavour.\nB It consists of three quarks that do not need to be the same flavour.\nC It consists of two quarks that must both be the same flavour.\nD It consists of two quarks that do not need to be the same flavour.", "img": "NULL"},
    {"q": "38", "text": "38 A stationary nucleus has nucleon number A.\nThe nucleus decays by emitting a proton with speed v to form a new nucleus with speed u. The new nucleus and the proton move away from one another in opposite directions.\nWhich equation gives v in terms of A and u?\nA v = (4A – 1)u\nB v = (A – 1)u\nC v = Au\nD v = (A + 1)u", "img": "NULL"},
    {"q": "39", "text": "39 What is the change to the quark composition of a nucleus that takes place during β+ decay?\nA down to antiup\nB down to up\nC up to antidown\nD up to down", "img": "NULL"},
    {"q": "40", "text": "40 What is the charge, in terms of the elementary charge e, on a charm quark?\nA –2/3 e\nB –1/3 e\nC +1/3 e\nD +2/3 e", "img": "NULL"}
]

with open(r"data\questions.csv", "a", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    for q in questions:
        writer.writerow(["9702", "2025", "March", "1", "2", q["q"], "NULL", "1", q["text"], q["img"]])
