import csv

# We structure the questions here.
questions = [
    {"q": "1", "text": "1 Which quantity is a scalar quantity?\nA force\nB momentum\nC velocity\nD work", "img": "NULL"},
    {"q": "2", "text": "2 What is the effect of a systematic error on the measurement of a physical quantity?\nA It limits the precision of the measured value.\nB It limits the range of values obtained in repeated measurements.\nC It results in repeated measurements having different values from each other.\nD It results in the measured value being different from the correct value.", "img": "NULL"},
    {"q": "3", "text": "3 A car is accelerated by a constant resultant force of 300 N for 5.0 s.\nThe variation with time of the velocity, in cm s–1, of the car is shown.\n[diagram]\nWhat is the mass of the car?\nA 13 kg\nB 1000 kg\nC 1300 kg\nD 10 000 kg", "img": "images/9702_m25_qp_12_q3.png"},
    {"q": "4", "text": "4 An aircraft, initially stationary on a runway, takes off with a speed of 85 km h–1 in a distance of no more than 1.20 km.\nWhat is the minimum constant acceleration necessary for the aircraft?\nA 0.23 m s–2\nB 0.46 m s–2\nC 3.0 m s–2\nD 6.0 m s–2", "img": "NULL"},
    {"q": "5", "text": "5 An object is fired upwards from horizontal ground. The object has an initial velocity of 20 m s–1 at an angle of 45° to the horizontal. Air resistance is negligible.\nWhich statement describes the speed of the object after it is fired until immediately before it reaches the ground again?\nA Its speed decreases to a value greater than zero, then increases to 20 m s–1.\nB Its speed decreases to a value greater than zero, then increases to a value greater than 20 m s–1.\nC Its speed decreases to zero, then increases to 20 m s–1.\nD Its speed decreases to zero, then increases to a value less than 20 m s–1.", "img": "NULL"},
    {"q": "6", "text": "6 What is a statement of the principle of conservation of momentum for a system?\nA The total momentum and the total kinetic energy are always conserved.\nB The total momentum is conserved only in elastic collisions.\nC The total momentum is conserved provided that no external forces act.\nD The total momentum of each object in the system is the product of its mass and velocity.", "img": "NULL"},
    {"q": "7", "text": "7 Objects P and Q form an isolated system.\nObject P has mass 6.0 kg and is moving at a speed of 3.0 m s–1.\nObject Q has mass 2.0 kg and is moving at a speed of 4.2 m s–1 at an angle of 35° to the path of P.\n[diagram]\nObjects P and Q collide and stick together.\nWhat is the magnitude of the component of the final momentum of the combined objects in the original direction of P?\nA 9.6 kg m s–1\nB 11 kg m s–1\nC 13 kg m s–1\nD 25 kg m s–1", "img": "images/9702_m25_qp_12_q7.png"},
    {"q": "8", "text": "8 An astronaut of mass m in a spacecraft experiences a gravitational force F = mg when stationary on the launchpad.\nWhat is the gravitational force on the astronaut when the spacecraft is launched vertically upwards with an acceleration of 0.2g?\nA 1.2mg\nB mg\nC 0.8mg\nD 0", "img": "NULL"},
    {"q": "9", "text": "9 The diagram shows a child X of mass 20 kg and a child Y of mass 15 kg seated on a uniform plank.\n[diagram]\nThe plank has a mass of 7.0 kg and has a pivot at its midpoint. The plank is horizontal and in equilibrium.\nWhich statement about the weight of the plank is correct?\nA The weight of the plank can be considered to be acting at its midpoint.\nB The weight of the plank is causing an anticlockwise moment.\nC The weight of the plank is causing a clockwise moment.\nD The weight of the plank equals the force on the plank from the pivot.", "img": "images/9702_m25_qp_12_q9.png"},
    {"q": "10", "text": "10 An object is fully submerged in a liquid.\nA student determines the ratio of upthrust acting on the object to the weight of the object.\nWhich single change would double the value of this ratio?\nA Use a different liquid that has twice the density and the same volume as the original liquid.\nB Use a different object that has half the volume and the same density as the original object.\nC Use a different object that has twice the density and the same volume as the original object.\nD Use a different object that has twice the volume and the same density as the original object.", "img": "NULL"},
    {"q": "11", "text": "11 A shop sign weighing 75 N hangs from a frame attached to a vertical wall.\n[diagram]\nThe frame consists of a horizontal rod XY and a rod YZ that is at an angle of 30° to the horizontal. Rod XY is attached to the wall by a hinge at X and has length 0.50 m. Assume that the weights of the rods are negligible.\nWhat is the horizontal force exerted by the wall on rod XY?\nA 0 N\nB 43 N\nC 130 N\nD 150 N", "img": "images/9702_m25_qp_12_q11.png"},
    {"q": "12", "text": "12 A student takes measurements to calculate the density of a liquid in a beaker.\nThe height of the liquid in the beaker is 0.20 m ± 2%.\nThe internal diameter of the beaker is 0.05 m ± 3%.\nThe mass of the liquid is 0.36 kg ± 10%.\nWhat is the percentage uncertainty in the calculated density of the liquid?\nA 2%\nB 5%\nC 15%\nD 18%", "img": "NULL"},
    {"q": "13", "text": "13 The diagram shows a uniform plank XY of length 4.0 m and weight 300 N.\n[diagram]\nThe plank rests on fixed supports at its ends X and Y.\nA child of weight 600 N stands in different positions on the plank.\nThe support at end X exerts a force F vertically upwards on the plank.\nWhat is the magnitude of F when the child stands at X and when the child stands at Y?\nOption A: 600N at X, 0N at Y\nOption B: 600N at X, 150N at Y\nOption C: 750N at X, 0N at Y\nOption D: 750N at X, 150N at Y", "img": "images/9702_m25_qp_12_q13.png"},
    {"q": "14", "text": "14 Which relationship is used in the derivation of the equation shown?\npower = force × velocity\nA displacement = velocity × time\nB force = mass × acceleration\nC momentum = mass × velocity\nD velocity = acceleration × time", "img": "NULL"},
    {"q": "15", "text": "15 A block is released from rest at the top of a slope inclined at an angle to the horizontal. The slope has length L as shown in the diagram.\n[diagram]\nThere are no resistive forces acting on the block.\nWhat is the speed of the block at the bottom of the slope?\nA 4.43 L cos θ\nB 4.43 L sin θ\nC 19.6 L cos θ\nD 19.6 L sin θ", "img": "images/9702_m25_qp_12_q15.png"},
    {"q": "16", "text": "16 A skateboarder and her skateboard have a total mass of 70 kg. She pushes on the ground with her foot to create a forward force F of 25 N on herself and the skateboard, as shown in the diagram.\n[diagram]\nThe skateboarder and skateboard travel forwards a distance of 0.50 m before the skateboarder lifts her foot from the ground.\nWhat is the work done by F on the skateboarder and skateboard?\nA 13 J\nB 50 J\nC 340 J\nD 360 J", "img": "images/9702_m25_qp_12_q16.png"},
    {"q": "17", "text": "17 A turbine at a hydroelectric power station is situated at a vertical distance of 30 m below the level of the surface of a large lake. The water passes through the turbine at a rate of 340 m3 per minute.\nThe overall efficiency of the turbine and generator system is 90%. The density of water is 1000 kg m–3.\nWhat is the useful power output of the power station?\nA 0.15 MW\nB 1.5 MW\nC 1.7 MW\nD 90 MW", "img": "NULL"},
    {"q": "18", "text": "18 A projectile is launched at 45° to the horizontal with initial kinetic energy E.\nAssuming air resistance to be negligible, what will be the kinetic energy of the projectile when it reaches its highest point?\nA 0.50E\nB 0.71E\nC 0.87E\nD E", "img": "NULL"},
    {"q": "19", "text": "19 A wire is extended by a tensile force so that its deformation is elastic.\nWhat is meant by elastic deformation?\nA The extension of the wire is proportional to the tensile force.\nB The extension of the wire is not proportional to the tensile force.\nC When the tensile force is removed, the wire does not return to its original length.\nD When the tensile force is removed, the wire returns to its original length.", "img": "NULL"},
    {"q": "20", "text": "20 A bolt is subjected to a tensile force, as shown.\n[diagram]\nThe bolt has a circular cross-section. At end X, the diameter is 2d. At end Y, the diameter is d.\nWhat is the ratio (stress at X) / (stress at Y)?\nA 0.25\nB 0.50\nC 2.0\nD 4.0", "img": "images/9702_m25_qp_12_q20.png"}
]

# Write parts 1-20
with open(r"data\questions.csv", "a", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    for q in questions:
        # subject_code,year,session,paper_number,variant,question_number,label,marks,text_statement,image_path
        writer.writerow(["9702", "2025", "March", "1", "2", q["q"], "NULL", "1", q["text"], q["img"]])
