import csv

er_comments = [
    {"q": "NULL", "lbl": "General", "text": "It is important to carefully read the text of the question before considering the answer options. In numerical questions, candidates should be careful to consider SI prefixes and powers of ten, as well as possible unit conversions, and should be encouraged to check to their answers to ensure they are a sensible magnitude. Candidates had particular difficulty resolving vectors into perpendicular components. Candidates should be able to select the correct trigonometric function for each problem and should be familiar with the inverse trigonometric functions. In general, candidates found Questions 5, 8, 23 and 36 relatively difficult. Candidates found Questions 1, 22, 34 and 40 relatively easy."},
    {"q": "3", "lbl": "NULL", "text": "This was answered well by most candidates. A significant number of weaker candidates selected option A, neglecting to convert the velocity units from cm s-1 to m s-1. Option B was also a common incorrect response, suggesting that candidates were not considering the change in velocity of the car. Candidates would benefit from more practice reading velocity-time graphs."},
    {"q": "4", "lbl": "NULL", "text": "Stronger candidates found this straightforward. The most common error among weaker candidates was to use the final velocity of the aircraft as 85 m s-1, rather than converting the 85 km h-1 to 23.6 m s-1 leading to option C. A significant minority converted correctly then used the incorrect formula v2 = u2 + as, neglecting the factor of 2."},
    {"q": "5", "lbl": "NULL", "text": "This proved challenging for candidates, with all 4 options selected roughly equally indicating that the variation of speed in two dimensions without air resistance is not well understood by most candidates. The question is best approached by considering conservation of energy. The projectile's speed must decrease as it rises, as kinetic energy decreases and gravitational potential energy increases. As the projectile is still in motion at its highest point the speed cannot decrease to zero, ruling out options C and D. The projectile then falls to its original height (ground level) so the speed must return to its original value, as the kinetic energy and gravitational potential energy return to their original values."},
    {"q": "7", "lbl": "NULL", "text": "Stronger candidates found this straightforward. The most common incorrect answer (D) was the result of adding the magnitudes of the correct components of momenta, neglecting that momentum is a vector quantity."},
    {"q": "8", "lbl": "NULL", "text": "Many candidates selected the incorrect options A and C for this question, attempting to find another force acting on the astronaut, despite the question asking for the gravitational force acting on the astronaut. Candidates are encouraged to carefully read the question and not to assume the quantity that they are being asked to find."},
    {"q": "11", "lbl": "NULL", "text": "Stronger candidates found this straightforward. Weaker candidates selected option B most frequently, which is the result of swapping sine and cosine when resolving the force in the wire. Candidates should practice resolving forces so they can confidently select the correct trigonometric functions."},
    {"q": "13", "lbl": "NULL", "text": "All candidates found this equilibrium challenging. A and C were the least popular options, suggesting that most candidates recognised that F would not be zero in either scenario. Option B was the most popular incorrect answer, with candidates perhaps considering only the weight of the child and neglecting the weight of the beam."},
    {"q": "15", "lbl": "NULL", "text": "Stronger candidates found this straightforward. The problem is best solved by resolving the acceleration of free fall into a component in the direction of the slope. Candidates who found this presentation of the problem unfamiliar could still have made progress by recognising 19.6 = 2g and relating this to v2 = u2 + 2as."},
    {"q": "18", "lbl": "NULL", "text": "Less than half of the candidates selected the correct answer A. The weakest candidates selected options B and D. In D no energy is lost, suggesting that candidates struggled to visualise this problem. Option B resulted from correctly determining the speed of the projectile at the maximum point compared with the initial speed then neglecting that that kinetic energy is proportional to the speed squared."},
    {"q": "21", "lbl": "NULL", "text": "Approximately two thirds of candidates recognised that the elastic potential energy could be determined using values from, or the area under, the graph. Incorrect option D, considering a single spring experiencing the whole 160 N force with extension 9.6 mm, was selected almost as often as the correct option B. For the correct answer candidates had to recognise that the four springs would share the 160 N force equally, and so each extends only 2.4 mm."},
    {"q": "23", "lbl": "NULL", "text": "This question required simple factual recall of the approximate wavelength of infrared radiation in free space. Fewer than half of candidates could recall this information, suggesting that this point on the syllabus is not well known."},
    {"q": "25", "lbl": "NULL", "text": "This was answered correctly by most candidates. The topic of phase difference is often challenging, and here it was also combined with the wave speed equation, suggesting that candidates understood this topic."},
    {"q": "29", "lbl": "NULL", "text": "This difficult question was answered correctly by half of the candidates, suggesting that diffraction grating problems are well understood by stronger candidates. Options A (the diffraction angle for the first order maximum) and B (the difference between the second and first order maxima) were equally popular. Candidates are encouraged to carefully read the question to ensure they are calculating the correct quantity."},
    {"q": "32", "lbl": "NULL", "text": "Option B was a very popular incorrect answer with nearly a third of candidates selecting it. Candidates choosing B perhaps confused the resistance against temperature profile of a thermistor with the required power against temperature profile. Candidates can reason that in this circuit the p.d. across the thermistor is constant, and recall that the resistance of the thermistor decreases with temperature. Candidates who therefore considered P = V2/R could identify option A as the correct answer."},
    {"q": "36", "lbl": "NULL", "text": "Candidates found this question challenging. Candidates who recognised that V represents the terminal p.d. and that with an open circuit this would be equal to the e.m.f. selected the correct option B. Option D was the most popular, with candidates confusing the concept of terminal p.d. and e.m.f.. Option A was also popular, with candidates perhaps neglecting that the measurement of V would include the e.m.f.. Candidates would benefit from practicing problems involving sources with internal resistance, and from practical experience of working with this kind of circuit."},
    {"q": "38", "lbl": "NULL", "text": "This question on conservation of momentum was answered well by most candidates."},
    {"q": "39", "lbl": "NULL", "text": "Around two thirds of candidates correctly answered this factual recall question. The most common incorrect answer was option B, indicating that students are not confident distinguishing between B+ and B- decay. The weakest candidates selected B, C and D equally, suggesting that the difference between quarks and antiquarks was not well understood."}
]

with open(r"data\examiner_comments.csv", "a", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    for c in er_comments:
        writer.writerow(["9702", "2025", "March", "1", "2", c["q"], c["lbl"], c["text"]])
